export enum TransactionType {
  INCOMING_UNKNOWN = 'INCOMING_UNKNOWN',

  INCOMING_FAST = 'INCOMING_FAST',

  INCOMING_SECURE = 'INCOMING_SECURE',

  FORWARD_MERCHANT = 'FORWARD_MERCHANT',

  FORWARD_HOLDINGS = 'FORWARD_HOLDINGS',
}
